### ISSUE TITLE
Tags: Unable to deselect tag + Change hover color

### ISSUE THREAD

**Issue by viktorsmari** [fablabbcn/smartcitizen-onboarding-app-iscape#15]
1. Unable to deselect the first tag I choose
2. When clicking a bubble, I am not sure if I have actually clicked it or not, because the color does not change.
3. Is there a limit on tags? I can only select 1

![2018-10-02_13-49-01](https://user-images.githubusercontent.com/1689020/46346911-f92a2080-c649-11e8-8da6-76022a80ebbb.png)

**Comment by dsmrs** [comment]
Note: only with "iOS user agent"
